### ISSUE TITLE
Unacceptable Attendance Conduct

### ISSUE THREAD

**Issue by laurennevill** [burgess01/code-of-conduct#1]
I made changes to a branch responsible for unacceptable conduct in attendance. The three standards I came up with are written below:

- Students should not arrive late to class if it can be helped.
- Students should not be absent from class or lab unless it is an excused absence.
- Students should not come to book club class sessions without reading the required assigned readings.

I tried to make issues of tardiness and absence open to valid excuse because I don't want them to seem to too harsh or unrealistic. If you can suggest any changes or additions, let me know.

**Comment by MAbraham24** [comment]
(For the second bullet point) I would recommended adding that "students should not be absent from class or lab unless it is an excused absence, or if you have communicated with the professor regarding your situation." This shows that students don't need to worry to much about the harshness of missing a class as they will receive help as long as they communicate.

**Comment by burgess01** [comment]
Maybe changing the wording of ' if it can be helped ' too ' without a valid excuse' to be more explicit with what you mean? Also, maybe adding something about out of class group project meetings and making sure to attend those if you agreed to?

**Comment by tuduun** [comment]
I agree with Michael. Also, I feel like the last bullet point is too harsh. I do not think it is fair to not allow a student into the class if he or she did not do the reading.

**Comment by laurennevill** [comment]
#10
